(ns the-family-tree.styles.utils.variables)

(def colours
  {:soft-blue "#E5F7FD"
   :light-blue "#D7F2FC"
   :hard-blue "#2DBCF0"
   :heavy-blue "#006699"
   :offset-blue "#76D3F5"
   :faded-blue "#ADE5F9"
   :soft-violet "#EAEAF4"
   :hard-violet "#2E3192"
   :faded-violet "#B1B2D7"
   :soft-pink "#FDE5F3"
   :hard-pink "#ED0F93"
   :faded-pink "#F8A4D6"
   :soft-crimson "#F9E7E8"
   :hard-crimson "#C4161C"
   :soft-yellow "#FEF6E8"
   :hard-yellow "#FAA61A"
   :faded-yellow "#FDDEA9"
   :soft-green "#F3F9EB"
   :hard-green "#8CC63F"
   :faded-green "#C0E095"
   :white "#FAFAFA"})
